### ISSUE TITLE
Identificar ajustes de conteúdo a partir do Refinamento

### ISSUE THREAD

**Issue by rodmaia** [lappis-unb/tais#109]
A análise das conversas do refinamento foi mapeada em #60.

A partir disso, precisamos identificar quais mudanças de conteúdo são necessárias e documentar essas mudanças para programá-las no roadmap.

-----------
**Critérios de aceitação**
- [ ] As mudanças de conteúdo estão listadas de forma que qualquer membro da equipe possa implementá-las sem precisar de discussões adicionais.

**Comment by rodmaia** [comment]
Planilha de compilação e resultados: https://docs.google.com/spreadsheets/d/1hb6chITZdLfqKfccMHMlTHHJ6645smdouFg72dwULTM/edit#gid=1927489573

Hipóteses sobre incoerências no fluxo: https://docs.google.com/document/d/1nFba6uRAW3CuMg38_g8fn6FaUIFNSRkdxKfv5bw9L5M/edit

**Comment by rodmaia** [comment]
@KahCosta e @palomacmamede revisei a análise que vocês fizeram e me parece que a gente pode tentar dividir os "problemas" em três grupos:

**Tópicos que Taís ainda não conhece**
Esses a gente teria que documentar em uma lista separada pois exige um planejamento antes de integrar. Acho que uma página da Wiki indicando o tópico novo e os exemplos de perguntas que as pessoas fizeram.

**Novas formas de perguntar tópicos que a Taís conhece**
Ainda não sei bem o melhor jeito de documentar isso. A princípio me parece algo que seria integrado como uma tarefa fixa à cada sprint. Precisa de um pouco de cuidado porque um novo sinônimo pode quebrar outros intents existentes. Acho que faz mais sentido abrir uma página na wiki do que abrir uma issue para cada novo tópico.

**Intents que a Taís classifica errado**
Acho que precisaríamos abrir uma issue para cada erro. Ao mesmo tempo, existe um volume muito grande de erros. Então, talvez devêssemos agrupar erros relacionados dentro de uma mesma issue?

O que acham? Podemos abrir a discussão para a equipe inteira. Provavelmente vamos usar essas decisões para tratar o feedback do beta também.

**Comment by MatheusFaria** [comment]
As mudanças de conteudo devem ser acordadas com a equipe. #152
